/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe_game;

import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.UnsupportedAudioFileException;

/**
 *
 * @author ASUS
 */
public class GameFrame extends javax.swing.JFrame {
    
    String player = "X";
    int X = 0;
    int Y = 0;
    
    /**
     * Creates new form GameFrame
     */
    public GameFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ScoreY = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ScoreX = new javax.swing.JLabel();
        StartB = new javax.swing.JButton();
        NewGameB = new javax.swing.JButton();
        ReStartB = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic Tac Toe");
        setLocation(new java.awt.Point(300, 100));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 204, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Chiller", 1, 48)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 204, 0));
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Chiller", 1, 48)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 204, 0));
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Chiller", 1, 48)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 204, 0));
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setFont(new java.awt.Font("Chiller", 1, 48)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 204, 0));
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(51, 51, 51));
        jButton5.setFont(new java.awt.Font("Chiller", 1, 48)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 204, 0));
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(51, 51, 51));
        jButton6.setFont(new java.awt.Font("Chiller", 1, 48)); // NOI18N
        jButton6.setForeground(new java.awt.Color(51, 204, 0));
        jButton6.setEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(51, 51, 51));
        jButton7.setFont(new java.awt.Font("Chiller", 1, 48)); // NOI18N
        jButton7.setForeground(new java.awt.Color(51, 204, 0));
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(51, 51, 51));
        jButton8.setFont(new java.awt.Font("Chiller", 1, 48)); // NOI18N
        jButton8.setForeground(new java.awt.Color(51, 204, 0));
        jButton8.setToolTipText("");
        jButton8.setEnabled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(51, 51, 51));
        jButton9.setFont(new java.awt.Font("Chiller", 1, 48)); // NOI18N
        jButton9.setForeground(new java.awt.Color(51, 204, 0));
        jButton9.setEnabled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Chiller", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Player Y: ");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 204, 0)));

        ScoreY.setFont(new java.awt.Font("Chiller", 1, 24)); // NOI18N
        ScoreY.setForeground(new java.awt.Color(255, 255, 255));
        ScoreY.setText("0");
        ScoreY.setToolTipText("");
        ScoreY.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 204, 0)));

        jLabel5.setFont(new java.awt.Font("Chiller", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Player X: ");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 204, 0)));

        ScoreX.setFont(new java.awt.Font("Chiller", 1, 24)); // NOI18N
        ScoreX.setForeground(new java.awt.Color(255, 255, 255));
        ScoreX.setText("0");
        ScoreX.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 204, 0)));

        StartB.setBackground(new java.awt.Color(102, 204, 0));
        StartB.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        StartB.setForeground(new java.awt.Color(51, 51, 51));
        StartB.setText("Start");
        StartB.setToolTipText("");
        StartB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartBActionPerformed(evt);
            }
        });

        NewGameB.setBackground(new java.awt.Color(102, 204, 0));
        NewGameB.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        NewGameB.setForeground(new java.awt.Color(51, 51, 51));
        NewGameB.setText("New Game");
        NewGameB.setToolTipText("");
        NewGameB.setEnabled(false);
        NewGameB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewGameBActionPerformed(evt);
            }
        });

        ReStartB.setBackground(new java.awt.Color(102, 204, 0));
        ReStartB.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        ReStartB.setForeground(new java.awt.Color(51, 51, 51));
        ReStartB.setText("ReStart");
        ReStartB.setToolTipText("");
        ReStartB.setEnabled(false);
        ReStartB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReStartBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(3, 3, 3)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ScoreX, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ScoreY, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NewGameB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ReStartB, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(StartB, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(ScoreX, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ScoreY, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(7, 7, 7)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NewGameB, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(StartB, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                .addComponent(ReStartB, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(12, 12, 12))
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 0));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe_game/Logo.png"))); // NOI18N
        jLabel2.setText("Tic Tac Toe");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReStartBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReStartBActionPerformed
        //
        jButton1.setText("");
        jButton2.setText("");
        jButton3.setText("");
        jButton4.setText("");
        jButton5.setText("");
        jButton6.setText("");
        jButton7.setText("");
        jButton8.setText("");
        jButton9.setText("");
        
        jButton1.setBackground(Color.BLACK);
        jButton2.setBackground(Color.BLACK);
        jButton3.setBackground(Color.BLACK);
        jButton4.setBackground(Color.BLACK);
        jButton5.setBackground(Color.BLACK);
        jButton6.setBackground(Color.BLACK);
        jButton7.setBackground(Color.BLACK);
        jButton8.setBackground(Color.BLACK);
        jButton9.setBackground(Color.BLACK);
            
        jButton1.setForeground(new Color(153,204,0));
        jButton2.setForeground(new Color(153,204,0));
        jButton3.setForeground(new Color(153,204,0));
        jButton4.setForeground(new Color(153,204,0));
        jButton5.setForeground(new Color(153,204,0));
        jButton6.setForeground(new Color(153,204,0));
        jButton7.setForeground(new Color(153,204,0));
        jButton8.setForeground(new Color(153,204,0));
        jButton9.setForeground(new Color(153,204,0));
        
         String Path = "C:\\Users\\ASUS\\Documents\\NetBeansProjects\\TicTacToe_Game\\src\\tictactoe_game\\ClickSound.wav";
        try {
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File(Path));
            Clip player = AudioSystem.getClip();
            player.open(audio);
            player.start();
            
        } catch (Exception ex) {
            
        } 
   
    }//GEN-LAST:event_ReStartBActionPerformed

    private void NewGameBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewGameBActionPerformed
        // 
        X=0;
        Y=0;
        ScoreX.setText("0");
        ScoreY.setText("0");
        
        jButton1.setText("");
        jButton2.setText("");
        jButton3.setText("");
        jButton4.setText("");
        jButton5.setText("");
        jButton6.setText("");
        jButton7.setText("");
        jButton8.setText("");
        jButton9.setText("");
        
        jButton1.setBackground(Color.BLACK);
        jButton2.setBackground(Color.BLACK);
        jButton3.setBackground(Color.BLACK);
        jButton4.setBackground(Color.BLACK);
        jButton5.setBackground(Color.BLACK);
        jButton6.setBackground(Color.BLACK);
        jButton7.setBackground(Color.BLACK);
        jButton8.setBackground(Color.BLACK);
        jButton9.setBackground(Color.BLACK);
            
        jButton1.setForeground(new Color(153,204,0));
        jButton2.setForeground(new Color(153,204,0));
        jButton3.setForeground(new Color(153,204,0));
        jButton4.setForeground(new Color(153,204,0));
        jButton5.setForeground(new Color(153,204,0));
        jButton6.setForeground(new Color(153,204,0));
        jButton7.setForeground(new Color(153,204,0));
        jButton8.setForeground(new Color(153,204,0));
        jButton9.setForeground(new Color(153,204,0));
        
         String Path = "C:\\Users\\ASUS\\Documents\\NetBeansProjects\\TicTacToe_Game\\src\\tictactoe_game\\ClickSound.wav";
        try {
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File(Path));
            Clip player = AudioSystem.getClip();
            player.open(audio);
            player.start();
            
        } catch (Exception ex) {
            
        } 
    }//GEN-LAST:event_NewGameBActionPerformed

    private void StartBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartBActionPerformed
        // 
        
         String Path = "C:\\Users\\ASUS\\Documents\\NetBeansProjects\\TicTacToe_Game\\src\\tictactoe_game\\ClickSound.wav";
        try {
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File(Path));
            Clip player = AudioSystem.getClip();
            player.open(audio);
            player.start();
            
        } catch (Exception ex) {
            
        } 
        
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton8.setEnabled(true);
        jButton9.setEnabled(true);
        NewGameB.setEnabled(true);
        ReStartB.setEnabled(true);
        
        
    }//GEN-LAST:event_StartBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //
        if(player=="X"){
            jButton1.setText(player);
            player = "O";
        }
        else{
            jButton1.setText(player);
            player = "X";
        }
        String Path = "C:\\Users\\ASUS\\Documents\\NetBeansProjects\\TicTacToe_Game\\src\\tictactoe_game\\ClickSound.wav";
        try {
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File(Path));
            Clip player = AudioSystem.getClip();
            player.open(audio);
            player.start();
            
        } catch (Exception ex) {
            
        } 
        gameWining();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //
        if(player=="X"){
            jButton4.setText(player);
            player = "O";
        }
        else{
            jButton4.setText(player);
            player = "X";
        }
         String Path = "C:\\Users\\ASUS\\Documents\\NetBeansProjects\\TicTacToe_Game\\src\\tictactoe_game\\ClickSound.wav";
        try {
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File(Path));
            Clip player = AudioSystem.getClip();
            player.open(audio);
            player.start();
            
        } catch (Exception ex) {
            
        } 
        gameWining();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //
        if(player=="X"){
            jButton2.setText(player);
            player = "O";
        }
        else{
            jButton2.setText(player);
            player = "X";
        }
         String Path = "C:\\Users\\ASUS\\Documents\\NetBeansProjects\\TicTacToe_Game\\src\\tictactoe_game\\ClickSound.wav";
        try {
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File(Path));
            Clip player = AudioSystem.getClip();
            player.open(audio);
            player.start();
            
        } catch (Exception ex) {
            
        } 
        gameWining();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //
        if(player=="X"){
            jButton3.setText(player);
            player = "O";
        }
        else{
            jButton3.setText(player);
            player = "X";
        }
        String Path = "C:\\Users\\ASUS\\Documents\\NetBeansProjects\\TicTacToe_Game\\src\\tictactoe_game\\ClickSound.wav";
        try {
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File(Path));
            Clip player = AudioSystem.getClip();
            player.open(audio);
            player.start();
            
        } catch (Exception ex) {
            
        } 
        gameWining();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //
        if(player=="X"){
            jButton5.setText(player);
            player = "O";
        }
        else{
            jButton5.setText(player);
            player = "X";
        }
        String Path = "C:\\Users\\ASUS\\Documents\\NetBeansProjects\\TicTacToe_Game\\src\\tictactoe_game\\ClickSound.wav";
        try {
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File(Path));
            Clip player = AudioSystem.getClip();
            player.open(audio);
            player.start();
            
        } catch (Exception ex) {
            
        } 
        gameWining();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //
        if(player=="X"){
            jButton6.setText(player);
            player = "O";
        }
        else{
            jButton6.setText(player);
            player = "X";
        }
        String Path = "C:\\Users\\ASUS\\Documents\\NetBeansProjects\\TicTacToe_Game\\src\\tictactoe_game\\ClickSound.wav";
        try {
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File(Path));
            Clip player = AudioSystem.getClip();
            player.open(audio);
            player.start();
            
        } catch (Exception ex) {
            
        } 
        gameWining();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        //
        if(player=="X"){
            jButton7.setText(player);
            player = "O";
        }
        else{
            jButton7.setText(player);
            player = "X";
        }
         String Path = "C:\\Users\\ASUS\\Documents\\NetBeansProjects\\TicTacToe_Game\\src\\tictactoe_game\\ClickSound.wav";
        try {
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File(Path));
            Clip player = AudioSystem.getClip();
            player.open(audio);
            player.start();
            
        } catch (Exception ex) {
            
        } 
        gameWining();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        //
        if(player=="X"){
            jButton8.setText(player);
            player = "O";
        }
        else{
            jButton8.setText(player);
            player = "X";
        }
         String Path = "C:\\Users\\ASUS\\Documents\\NetBeansProjects\\TicTacToe_Game\\src\\tictactoe_game\\ClickSound.wav";
        try {
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File(Path));
            Clip player = AudioSystem.getClip();
            player.open(audio);
            player.start();
            
        } catch (Exception ex) {
            
        } 
        gameWining();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        //
        if(player=="X"){
            jButton9.setText(player);
            player = "O";
        }
        else{
            jButton9.setText(player);
            player = "X";
        }
         String Path = "C:\\Users\\ASUS\\Documents\\NetBeansProjects\\TicTacToe_Game\\src\\tictactoe_game\\ClickSound.wav";
        try {
            AudioInputStream audio = AudioSystem.getAudioInputStream(new File(Path));
            Clip player = AudioSystem.getClip();
            player.open(audio);
            player.start();
            
        } catch (Exception ex) {
            
        } 
        gameWining();
    }//GEN-LAST:event_jButton9ActionPerformed
        
    private void gameWining(){
        String A = jButton1.getText();
        String B = jButton2.getText();
        String C = jButton3.getText();
        String D = jButton4.getText();
        String E = jButton5.getText();
        String F = jButton6.getText();
        String G = jButton7.getText();
        String H = jButton8.getText();
        String I = jButton9.getText();
        
        //for x
        if(A=="X" && A==B && B==C){
            WinningFrame Win = new WinningFrame();
            Win.setwin("X");
            Win.setVisible(true);
            
            X++;
            ScoreX.setText(Integer.toString(X));
            
            jButton1.setBackground(new Color(153,204,0));
            jButton2.setBackground(new Color(153,204,0));
            jButton3.setBackground(new Color(153,204,0));
            
            jButton1.setForeground(Color.BLACK);
            jButton2.setForeground(Color.BLACK);
            jButton3.setForeground(Color.BLACK);
            
        }
        else if(D=="X" && D==E && E==F){
            WinningFrame Win = new WinningFrame();
            Win.setwin("X");
            Win.setVisible(true);
            
            X++;
            ScoreX.setText(Integer.toString(X));
            
            jButton4.setBackground(new Color(153,204,0));
            jButton5.setBackground(new Color(153,204,0));
            jButton6.setBackground(new Color(153,204,0));
            
            jButton4.setForeground(Color.BLACK);
            jButton5.setForeground(Color.BLACK);
            jButton6.setForeground(Color.BLACK);
        }
        else if(G=="X" && G==H && H==I){
            WinningFrame Win = new WinningFrame();
            Win.setwin("X");
            Win.setVisible(true);
            
            X++;
            ScoreX.setText(Integer.toString(X));
            
            jButton7.setBackground(new Color(153,204,0));
            jButton8.setBackground(new Color(153,204,0));
            jButton9.setBackground(new Color(153,204,0));
            
            jButton7.setForeground(Color.BLACK);
            jButton8.setForeground(Color.BLACK);
            jButton9.setForeground(Color.BLACK);
        }
        else if(A=="X" && A==D && D==G){
            WinningFrame Win = new WinningFrame();
            Win.setwin("X");
            Win.setVisible(true);
            
            X++;
            ScoreX.setText(Integer.toString(X));
            
            jButton1.setBackground(new Color(153,204,0));
            jButton4.setBackground(new Color(153,204,0));
            jButton7.setBackground(new Color(153,204,0));
            
            jButton1.setForeground(Color.BLACK);
            jButton4.setForeground(Color.BLACK);
            jButton7.setForeground(Color.BLACK);
        }
        else if(B=="X" && B==E && E==H){
            WinningFrame Win = new WinningFrame();
            Win.setwin("X");
            Win.setVisible(true);
            
            X++;
            ScoreX.setText(Integer.toString(X));
            
            jButton2.setBackground(new Color(153,204,0));
            jButton5.setBackground(new Color(153,204,0));
            jButton8.setBackground(new Color(153,204,0));
            
            jButton2.setForeground(Color.BLACK);
            jButton5.setForeground(Color.BLACK);
            jButton8.setForeground(Color.BLACK);
        }
        else if(C=="X" && C==F && F==I){
            WinningFrame Win = new WinningFrame();
            Win.setwin("X");
            Win.setVisible(true);
            
            X++;
            ScoreX.setText(Integer.toString(X));
            
            jButton3.setBackground(new Color(153,204,0));
            jButton6.setBackground(new Color(153,204,0));
            jButton9.setBackground(new Color(153,204,0));
            
            jButton3.setForeground(Color.BLACK);
            jButton6.setForeground(Color.BLACK);
            jButton9.setForeground(Color.BLACK);
        }
        else if(A=="X" && A==E && E==I){
            WinningFrame Win = new WinningFrame();
            Win.setwin("X");
            Win.setVisible(true);
            
            X++;
            ScoreX.setText(Integer.toString(X));
            
            jButton1.setBackground(new Color(153,204,0));
            jButton5.setBackground(new Color(153,204,0));
            jButton9.setBackground(new Color(153,204,0));
            
            jButton1.setForeground(Color.BLACK);
            jButton5.setForeground(Color.BLACK);
            jButton9.setForeground(Color.BLACK);
        }
        else if(C=="X" && C==E && E==G){
            WinningFrame Win = new WinningFrame();
            Win.setwin("X");
            Win.setVisible(true);
            
            X++;
            ScoreX.setText(Integer.toString(X));
            
            jButton3.setBackground(new Color(153,204,0));
            jButton5.setBackground(new Color(153,204,0));
            jButton7.setBackground(new Color(153,204,0));
            
            jButton3.setForeground(Color.BLACK);
            jButton5.setForeground(Color.BLACK);
            jButton7.setForeground(Color.BLACK);
        }
        
        //for O
        if(A=="O" && A==B && B==C){
            WinningFrame Win = new WinningFrame();
            Win.setwin("O");
            Win.setVisible(true);
            
            Y++;
            ScoreY.setText(Integer.toString(Y));
            
            jButton1.setBackground(new Color(153,204,0));
            jButton2.setBackground(new Color(153,204,0));
            jButton3.setBackground(new Color(153,204,0));
            
            jButton1.setForeground(Color.BLACK);
            jButton2.setForeground(Color.BLACK);
            jButton3.setForeground(Color.BLACK);
        }
        else if(D=="O" && D==E && E==F){
            WinningFrame Win = new WinningFrame();
            Win.setwin("O");
            Win.setVisible(true);
            
            Y++;
            ScoreY.setText(Integer.toString(Y));
            
            jButton4.setBackground(new Color(153,204,0));
            jButton5.setBackground(new Color(153,204,0));
            jButton6.setBackground(new Color(153,204,0));
            
            jButton4.setForeground(Color.BLACK);
            jButton5.setForeground(Color.BLACK);
            jButton6.setForeground(Color.BLACK);
        }
        else if(G=="O" && G==H && H==I){
            WinningFrame Win = new WinningFrame();
            Win.setwin("O");
            Win.setVisible(true);
            
            Y++;
            ScoreY.setText(Integer.toString(Y));
            
            jButton7.setBackground(new Color(153,204,0));
            jButton8.setBackground(new Color(153,204,0));
            jButton9.setBackground(new Color(153,204,0));
            
            jButton7.setForeground(Color.BLACK);
            jButton8.setForeground(Color.BLACK);
            jButton9.setForeground(Color.BLACK);
        }
        else if(A=="O" && A==D && D==G){
            WinningFrame Win = new WinningFrame();
            Win.setwin("O");
            Win.setVisible(true);
            
            Y++;
            ScoreY.setText(Integer.toString(Y));
            
            jButton1.setBackground(new Color(153,204,0));
            jButton4.setBackground(new Color(153,204,0));
            jButton7.setBackground(new Color(153,204,0));
            
            jButton1.setForeground(Color.BLACK);
            jButton4.setForeground(Color.BLACK);
            jButton7.setForeground(Color.BLACK);
        }
        else if(B=="O" && B==E && E==H){
            WinningFrame Win = new WinningFrame();
            Win.setwin("O");
            Win.setVisible(true);
            
            Y++;
            ScoreY.setText(Integer.toString(Y));
            
            jButton2.setBackground(new Color(153,204,0));
            jButton5.setBackground(new Color(153,204,0));
            jButton8.setBackground(new Color(153,204,0));
            
            jButton2.setForeground(Color.BLACK);
            jButton5.setForeground(Color.BLACK);
            jButton8.setForeground(Color.BLACK);
        }
        else if(C=="O" && C==F && F==I){
            WinningFrame Win = new WinningFrame();
            Win.setwin("O");
            Win.setVisible(true);
            
            Y++;
            ScoreY.setText(Integer.toString(Y));
            
            jButton3.setBackground(new Color(153,204,0));
            jButton6.setBackground(new Color(153,204,0));
            jButton9.setBackground(new Color(153,204,0));
            
            jButton3.setForeground(Color.BLACK);
            jButton6.setForeground(Color.BLACK);
            jButton9.setForeground(Color.BLACK);
        }
        else if(A=="O" && A==E && E==I){
            WinningFrame Win = new WinningFrame();
            Win.setwin("O");
            Win.setVisible(true);
            
            Y++;
            ScoreY.setText(Integer.toString(Y));
            
            jButton1.setBackground(new Color(153,204,0));
            jButton5.setBackground(new Color(153,204,0));
            jButton9.setBackground(new Color(153,204,0));
            
            jButton1.setForeground(Color.BLACK);
            jButton5.setForeground(Color.BLACK);
            jButton9.setForeground(Color.BLACK);
        }
        else if(C=="O" && C==E && E==G){
            WinningFrame Win = new WinningFrame();
            Win.setwin("O");
            Win.setVisible(true);
            
            Y++;
            ScoreY.setText(Integer.toString(Y));
            
            jButton3.setBackground(new Color(153,204,0));
            jButton5.setBackground(new Color(153,204,0));
            jButton7.setBackground(new Color(153,204,0));
            
            jButton3.setForeground(Color.BLACK);
            jButton5.setForeground(Color.BLACK);
            jButton7.setForeground(Color.BLACK);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NewGameB;
    private javax.swing.JButton ReStartB;
    private javax.swing.JLabel ScoreX;
    private javax.swing.JLabel ScoreY;
    private javax.swing.JButton StartB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
